version: '3'
services:
  springboot-app:
    build:
      context: .
      dockerfile: teezinator/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    build: 
      context: .
      dockerfile: teezinator-db/Dockerfile
    ports:
      - "27022:27017"
    networks:
      - my-network

  react-app:
    build:
      context: .
      dockerfile: teezinator-client/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network
    env_file:
      - .env
    depends_on:
      - springboot-app

networks:
  my-network: {}
